### PR TITLE
Adding http2 in nginx

### PR DESCRIPTION
**Pull request by jonatanaxe**
Hi @faradey , can we add HTTP/2?

### CODE REVIEW

**Comment by faradey** [comment]
@jonatanaxe 
Greetings, that’s a great suggestion.  

I believe enabling **HTTP/2** by default makes sense. However, it’s a good idea to include an additional configuration option to allow reverting to HTTP if necessary. For example:  

`{{{nginx/http/version}}}`  

In this case, the full configuration line would look like this:  
`listen {{{nginx/port/secure}}} ssl {{{nginx/http/version}}};`  

By default, in the `/config.xml` file, the value could be set to **HTTP/2**. If needed, the user could leave this setting empty (remove the HTTP/2 value), which would then convert the configuration from:  
`listen 443 ssl http2;`  
to  
`listen 443 ssl;`  

What do you think about this approach? Would you be able to implement this?

**Comment by jonatanaxe** [comment]
Hi @faradey , I added the additional configuration. Could you please test it?

**Review by faradey — APPROVED** [review]

**Comment by faradey** [comment]
@jonatanaxe hi, I've accepted your request. I’ve made some adjustments to the configuration to ensure it works correctly. In the future, it might make sense to implement this so that the added configuration is applied automatically without needing changes to the Go code. Please update your build and take a look at my latest commit.

**Comment by jonatanaxe** [comment]
@faradey Hi, I didn't know I had to make changes in Go, but it makes sense. It's good to know how you do that!

**Pull request merged**
